//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace brainHatSharpGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("brainHatSharpGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brainHat Server.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias Drn..
        /// </summary>
        public static string BiasDrn {
            get {
                return ResourceManager.GetString("BiasDrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias Drp..
        /// </summary>
        public static string BiasDrp {
            get {
                return ResourceManager.GetString("BiasDrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias.Meas..
        /// </summary>
        public static string BiasMeas {
            get {
                return ResourceManager.GetString("BiasMeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias Measured.
        /// </summary>
        public static string BiasMeasured {
            get {
                return ResourceManager.GetString("BiasMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias Set.
        /// </summary>
        public static string BiasSet {
            get {
                return ResourceManager.GetString("BiasSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Configuration.
        /// </summary>
        public static string ChannelConfig {
            get {
                return ResourceManager.GetString("ChannelConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must close the configuration window before stopping the server..
        /// </summary>
        public static string CloseConfigWindowBeforeStoppingServer {
            get {
                return ResourceManager.GetString("CloseConfigWindowBeforeStoppingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Port.
        /// </summary>
        public static string ComPort {
            get {
                return ResourceManager.GetString("ComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Board.
        /// </summary>
        public static string ConfigureBoard {
            get {
                return ResourceManager.GetString("ConfigureBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to board.
        /// </summary>
        public static string ConnectingToBoard {
            get {
                return ResourceManager.GetString("ConnectingToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect SRB1.
        /// </summary>
        public static string ConnectSRB1 {
            get {
                return ResourceManager.GetString("ConnectSRB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do not connect SRB1.
        /// </summary>
        public static string ConnectSRB1Not {
            get {
                return ResourceManager.GetString("ConnectSRB1Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration.
        /// </summary>
        public static string CurrentConfig {
            get {
                return ResourceManager.GetString("CurrentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stream.
        /// </summary>
        public static string DataStream {
            get {
                return ResourceManager.GetString("DataStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Signal.
        /// </summary>
        public static string DCSignal {
            get {
                return ResourceManager.GetString("DCSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable brainflow streaming.
        /// </summary>
        public static string EnableBrainflowStreaming {
            get {
                return ResourceManager.GetString("EnableBrainflowStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Brainflow Streaming.
        /// </summary>
        public static string EnableBrainflowStreamingLabel {
            get {
                return ResourceManager.GetString("EnableBrainflowStreamingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do not enable brainflow streaming.
        /// </summary>
        public static string EnableBrainflowStreamingNot {
            get {
                return ResourceManager.GetString("EnableBrainflowStreamingNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Configuration.
        /// </summary>
        public static string EquipmentConfiguration {
            get {
                return ResourceManager.GetString("EquipmentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get valid board configuration..
        /// </summary>
        public static string FailedGetValidConfig {
            get {
                return ResourceManager.GetString("FailedGetValidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap greenLight {
            get {
                object obj = ResourceManager.GetObject("greenLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        public static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impedance Settings.
        /// </summary>
        public static string ImpedanceConfig {
            get {
                return ResourceManager.GetString("ImpedanceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in BIAS.
        /// </summary>
        public static string IncludeInBias {
            get {
                return ResourceManager.GetString("IncludeInBias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Type.
        /// </summary>
        public static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid COM Port.
        /// </summary>
        public static string InvalidComPort {
            get {
                return ResourceManager.GetString("InvalidComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Console to File.
        /// </summary>
        public static string LogToFile {
            get {
                return ResourceManager.GetString("LogToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must stop streaming before sending command..
        /// </summary>
        public static string MustStopStreamingBeforeSendingCommand {
            get {
                return ResourceManager.GetString("MustStopStreamingBeforeSendingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mvdd.
        /// </summary>
        public static string Mvdd {
            get {
                return ResourceManager.GetString("Mvdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying board parameters ....
        /// </summary>
        public static string QueryBoardParams {
            get {
                return ResourceManager.GetString("QueryBoardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading data from the board.
        /// </summary>
        public static string ReadingData {
            get {
                return ResourceManager.GetString("ReadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not reading data from the board.
        /// </summary>
        public static string ReadingDataNot {
            get {
                return ResourceManager.GetString("ReadingDataNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redLight {
            get {
                object obj = ResourceManager.GetObject("redLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from BIAS.
        /// </summary>
        public static string RemoveFromBias {
            get {
                return ResourceManager.GetString("RemoveFromBias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying.
        /// </summary>
        public static string Retrying {
            get {
                return ResourceManager.GetString("Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Channel(s).
        /// </summary>
        public static string SetChannels {
            get {
                return ResourceManager.GetString("SetChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Defaults.
        /// </summary>
        public static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Impedance(s).
        /// </summary>
        public static string SetImpedance {
            get {
                return ResourceManager.GetString("SetImpedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Test Mode.
        /// </summary>
        public static string SetTestMode {
            get {
                return ResourceManager.GetString("SetTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting channels.
        /// </summary>
        public static string SettingChannels {
            get {
                return ResourceManager.GetString("SettingChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting channels to default.
        /// </summary>
        public static string SettingChannelsDefault {
            get {
                return ResourceManager.GetString("SettingChannelsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting signal test mode.
        /// </summary>
        public static string SettingSignalTestMode {
            get {
                return ResourceManager.GetString("SettingSignalTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorted.
        /// </summary>
        public static string Shorted {
            get {
                return ResourceManager.GetString("Shorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRB1.
        /// </summary>
        public static string SRB1 {
            get {
                return ResourceManager.GetString("SRB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRB1 is.
        /// </summary>
        public static string SrbIs {
            get {
                return ResourceManager.GetString("SrbIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start the server before using Configure Board..
        /// </summary>
        public static string StartServerBeforeConfigure {
            get {
                return ResourceManager.GetString("StartServerBeforeConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Stream.
        /// </summary>
        public static string StartStream {
            get {
                return ResourceManager.GetString("StartStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with SRB1 Connected.
        /// </summary>
        public static string StartWithSrb {
            get {
                return ResourceManager.GetString("StartWithSrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        public static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Stream.
        /// </summary>
        public static string StopStream {
            get {
                return ResourceManager.GetString("StopStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data stream running.
        /// </summary>
        public static string StreamRunning {
            get {
                return ResourceManager.GetString("StreamRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data stream stopped.
        /// </summary>
        public static string StreamStopped {
            get {
                return ResourceManager.GetString("StreamStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp..
        /// </summary>
        public static string Temporary {
            get {
                return ResourceManager.GetString("Temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Sig..
        /// </summary>
        public static string TestSig {
            get {
                return ResourceManager.GetString("TestSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Signal.
        /// </summary>
        public static string TestSignal {
            get {
                return ResourceManager.GetString("TestSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test signal applied.
        /// </summary>
        public static string TestSignalApplied {
            get {
                return ResourceManager.GetString("TestSignalApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test signal not applied.
        /// </summary>
        public static string TestSignalNotApplied {
            get {
                return ResourceManager.GetString("TestSignalNotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Console.
        /// </summary>
        public static string ViewConsole {
            get {
                return ResourceManager.GetString("ViewConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yellowLight {
            get {
                object obj = ResourceManager.GetObject("yellowLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
